### ISSUE TITLE
Cyclic References cause a StackOverflowError

### ISSUE THREAD

**Issue by ParaPenguin** [ParaPenguin/morphix#2]
```
[15:20:36 WARN]: [Core] Task #4 for Core v3.0-ALPHA-dee175f generated an exception
java.lang.StackOverflowError
        at java.lang.Character.digit(Character.java:6563) ~[?:1.8.0_40-internal]
        at java.lang.Character.digit(Character.java:6511) ~[?:1.8.0_40-internal]
        at java.lang.Integer.parseInt(Integer.java:578) ~[?:1.8.0_40-internal]
        at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_40-internal]
        at org.bson.types.BasicBSONList._getInt(BasicBSONList.java:161) ~[?:?]
        at org.bson.types.BasicBSONList._getInt(BasicBSONList.java:156) ~[?:?]
        at org.bson.types.BasicBSONList.get(BasicBSONList.java:108) ~[?:?]
        at com.mongodb.DBCollection._checkKeys(DBCollection.java:1804) ~[?:?]
        at com.mongodb.DBCollection._checkValue(DBCollection.java:1826) ~[?:?]
        at com.mongodb.DBCollection._checkKeys(DBCollection.java:1804) ~[?:?]
        at com.mongodb.DBCollection._checkValue(DBCollection.java:1826) ~[?:?]
        at com.mongodb.DBCollection._checkKeys(DBCollection.java:1804) ~[?:?]
        at com.mongodb.DBCollection._checkValue(DBCollection.java:1826) ~[?:?]
        at com.mongodb.DBCollection._checkKeys(DBCollection.java:1804) ~[?:?]
        at com.mongodb.DBCollection._checkValue(DBCollection.java:1826) ~[?:?]
```

This error is caused by a cyclic reference, eg Player references Island, and Island references Player, which references Island, and so on.

**Comment by ParaPenguin** [comment]
Was an issue with how the project using Morphix was written, a bunch of forgotten references
